services:
  - type: web
    name: plc-school-system
    env: node
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PG_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
